name: test

on: [push]

jobs:
  build:
    name: ${{ matrix.os }} ${{ matrix.version }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest] # TODO: reenable macos-latest
        version: ["stable"]
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: "8"

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Compile
        run: pnpm run vscode:prepublish

      - name: Run tests
        uses: coactions/setup-xvfb@ab4686bf3d3328f3a96cd13874243d7c83d9cf84
        with:
          run: pnpm test
        env:
          CODE_VERSION: ${{ matrix.version }}

      - name: Lint check
        run: pnpm run lint
        if: ${{ matrix.os == 'ubuntu-latest' && matrix.version == 'stable' }}
